#docker-compose.yml (Base)
services:
  app:
    container_name: dev-demo-app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args: # these variables are available on build
        VERSION: ${PYTHON_IMAGE_VERSION}
    environment: # these variables are available on run
      PRODUCTION: true
    volumes:
      - data:${PATH_DATA}
volumes:
  data: